version: "3"
services:
  localstack:
    image: localstack/localstack:latest # see https://github.com/localstack/localstack/issues/1992 for issue with latest version
    environment:
      SERVICES: "sqs,sns"
      DEFAULT_REGION: "eu-west-1"
      HOSTNAME_EXTERNAL: "localhost"
      DEBUG: "1"
    ports:
      - "4566-4593:4566-4593"
      - "8082:8080"


